# Generated by Django 3.1.3 on 2020-11-27 22:31

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Məzmun'),
        ),
        migrations.AlterField(
            model_name='question',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AlterField(
            model_name='question',
            name='view',
            field=models.IntegerField(default=0, verbose_name='Baxış sayı'),
        ),
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.ImageField(upload_to='profile_images', verbose_name='Şəkil'),
        ),
    ]
