# Generated by Django 3.1.3 on 2020-12-01 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('student', '0002_auto_20201128_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Məzmun')),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='taggit.tag')),
            ],
            options={
                'verbose_name': 'TagInfo',
                'verbose_name_plural': 'TagInfos',
            },
        ),
    ]
