# Generated by Django 3.1.3 on 2020-11-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_questionimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images', verbose_name='Sualın şəkli'),
        ),
    ]
