# Generated by Django 3.1.3 on 2020-11-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_category_faq_question_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ManyToManyField(to='student.Category', verbose_name='Kategoriya'),
        ),
    ]
